### ISSUE TITLE
Feature : Being able to have multiple sources of the same provider with filters

### ISSUE THREAD

**Issue by Sabrimjd** [Sabrimjd/SSHPlex#16]
Change the config file to lists:

sources:
```yaml
# Source of Truth configuration
sot:
  providers: ["static", "netbox", "ansible"]  # Available: static, netbox, ansible
  import:
    - name: "production-servers"
      type: static
      hosts:
        - name: "web-server-01"
          ip: "192.168.1.10"
          description: "Production web server"
          tags: ["web", "production"]
        - name: "db-server-01"
          ip: "192.168.1.20"
          description: "Primary database server"
          tags: ["database", "production"]
    - name: "test-servers"
      type: static
      hosts:
        - name: "test-web-01"
          ip: "192.168.2.10"
          description: "Test web server"
          tags: ["web", "test"]
    - name: "primary-netbox"
      type: netbox
      url: "https://netbox.lan/"
      token: "CHANGE_TOKEN_HERE"
      verify_ssl: false
      timeout: 30
      default_filters:
        status: "active"
        role: "virtual-machine"
        has_primary_ip: "true"
    - name: "secondary-netbox"
      type: netbox
      url: "https://netbox2.lan/"
      token: "CHANGE_TOKEN_HERE_2"
      verify_ssl: false
      timeout: 30
      default_filters:
        status: "active"
        role: "router"
        has_primary_ip: "true"
    - name: "production-inventory"
      type: ansible
      inventory_paths:
        - "/path/to/production/inventory.yml"
      default_filters:
        groups: ["webservers", "databases"]
        exclude_groups: []
        host_patterns: []
    - name: "staging-inventory"
      type: ansible
      inventory_paths:
        - "/path/to/staging/inventory.yml"
        - "/path/to/staging/additional.yml"
      default_filters:
        groups: []
        exclude_groups: ["maintenance"]
        host_patterns: ["^staging-.*"]
```
